<?php

namespace Busybee\AVETMISS\AVETMISSBundle\Repository;

use Busybee\AVETMISS\AVETMISSBundle\Entity\Client;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

	public function findOneByStudent($student)
	{
		$client = parent::findOneByStudent($student);
		if (!$client instanceof Client)
			$client = new Client();

		return $client;
	}
}
