<?php

namespace Busybee\People\StaffBundle\Repository;

use Busybee\People\StaffBundle\Entity\Staff;
use Doctrine\ORM\EntityRepository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends EntityRepository
{
	/**
	 * @param   integer $personID
	 *
	 * @return  Staff
	 */
	public function findOneByPerson($personID)
	{
		$staff = parent::findOneByPerson($personID);

		return $staff instanceof Staff ? $staff : new Staff();
	}
}
