<?php

namespace Busybee\People\ContactBundle\Repository;

use Busybee\People\ContactBundle\Entity\Contact;
use Busybee\People\PersonBundle\Repository\PersonRepository;
use Busybee\People\StaffBundle\Entity\Staff;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends PersonRepository
{
	/**
	 * @param   integer $personID
	 *
	 * @return  Staff
	 */
	public function findOneByPerson($personID)
	{
		$contact = parent::find($personID);

		return $contact instanceof Contact ? $contact : new Contact();
	}

}
