<?php

namespace Busybee\StudentBundle\Repository;

/**
 * EnrolmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnrolmentRepository extends \Doctrine\ORM\EntityRepository
{
}
