<?php

namespace Busybee\People\StudentBundle\Repository;

use Busybee\People\PersonBundle\Entity\Person;
use Busybee\People\StudentBundle\Entity\Student;
use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
}
