<?php

namespace Busybee\People\StudentBundle\Repository;

use Busybee\People\PersonBundle\Entity\Person;
use Busybee\People\StudentBundle\Entity\Student;
use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
	/**
	 * @param   integer $personID
	 *
	 * @return  Student
	 */
	public function findOneByPerson($personID)
	{
		$student = parent::find($personID);

		$student = $student instanceof Person ? $student : new Person();

		$student->setPersonType('student');

		return $student;
	}
}
