<?php

namespace Busybee\People\StudentBundle\Repository;

use Busybee\People\StudentBundle\Entity\Student;
use Doctrine\ORM\EntityRepository;

/**
 * StudentGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentGradeRepository extends EntityRepository
{
}
