<?php
namespace Busybee\People\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Student Calendar Group Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentCalendarGroupRepository extends EntityRepository
{
}
