<?php

namespace Busybee\Core\CalendarBundle\Repository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends \Doctrine\ORM\EntityRepository
{
}
