<?php

namespace Busybee\InstituteBundle\Repository;

use Busybee\InstituteBundle\Entity\Year;

/**
 * YearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find Current Year
	 *
	 * @return Year
	 */
	public function findCurrentYear(): Year
	{
		$year = null;
		try
		{
			$year = $this->createQueryBuilder('y')
				->where('y.status = :status')
				->setParameter('status', 'current')
				->getQuery()
				->getSingleResult();
		}
		catch (\Exception $e)
		{
			$year = $this->generateYear();
		}

		if (!$year instanceof Year)
		{
			$year = $this->generateYear();
		}

		return $year;
	}

	/**
	 * Generate Year
	 *
	 * @return Year
	 */
	private function generateYear(): Year
	{
		$year = new Year();
		$year->setName(date('Y') . ' - Generated');
		$year->setStatus('current');
		$year->setFirstDay(new \DateTime(date('Y') . '-01-01 00:00:00'));
		$year->setLastDay(new \DateTime(date('Y') . '-12-31 00:00:00'));

		return $year;
	}
}
