<?php

namespace Busybee\People\FamilyBundle\Repository;

/**
 * CareGiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareGiverRepository extends \Doctrine\ORM\EntityRepository
{
}
