<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * CampusResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampusResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
