<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * DepartmentStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
