<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * HomeRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
