<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * SpaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpaceRepository extends \Doctrine\ORM\EntityRepository
{
}
