<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * SpecialDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialDayRepository extends \Doctrine\ORM\EntityRepository
{
}
