<?php

namespace Busybee\InstituteBundle\Repository;

/**
 * StudentYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentYearRepository extends \Doctrine\ORM\EntityRepository
{
}
