<?php

namespace Busybee\InstituteBundle\Repository;

use Busybee\InstituteBundle\Entity\StudentYear;
use Doctrine\ORM\EntityRepository;

/**
 * StudentYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentYearRepository extends EntityRepository
{
    /**
     * find One By Year Sequence
     *
     * @param $year
     * @param $sequence
     * @return StudentYear
     */
    public function findOneByYearSequence($year, $sequence)
    {
        $sy = $this->findOneBy(array('year' => $year, 'sequence' => $sequence));

        if (!$sy instanceof StudentYear)
            $sy = new StudentYear();
        return $sy;
    }
}
