<?php

namespace Busybee\InstituteBundle\Repository;

use Busybee\InstituteBundle\Entity\Year;

/**
 * YearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Year
     */
    public function findCurrentYear()
    {
        $today = new \DateTime();

        $year = $this->createQueryBuilder('y')
            ->where('y.firstDay <= :firstDay')
            ->andWhere('y.lastDay >= :lastDay')
            ->setParameter('lastDay', $today)
            ->setParameter('firstDay', $today)
            ->getQuery()
            ->getResult();

        if (is_array($year) and count($year) === 1)
            $year = reset($year);

        if (!$year instanceof Year)
            $year = new Year();

        return $year;
    }
}
