<?php

namespace Busybee\FamilyBundle\Repository ;

use Busybee\FamilyBundle\Entity\Family ;
use Doctrine\ORM\EntityRepository ;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends EntityRepository
{
    /**
     * @param mixed $id
     * @param integer $lockMode
     * @param integer $lockVersion
     * @return Family|null|object
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        if ($id === 'Add') return new Family();
        return parent::find($id, $lockMode, $lockVersion);
    }
}
