<?php

namespace Busybee\FamilyBundle\Repository;

/**
 * FamilyCareGiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyCareGiverRepository extends \Doctrine\ORM\EntityRepository
{
}
