<?php

namespace Busybee\FamilyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyCareGiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyCareGiverRepository extends EntityRepository
{
}
