<?php

namespace Busybee\FamilyBundle\Repository;

use Busybee\FamilyBundle\Entity\Family;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id)
    {
        $family = parent::find($id);
        return $family instanceof Family ? $family : new Family();
    }
}
