<?php
namespace Busybee\SecurityBundle\Repository;

use Busybee\SecurityBundle\Entity\Page;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByRoute($routeName): Page
    {
        $page = parent::findOneByRoute($routeName);

        if (empty($page)) {
            $page = new Page();
            $page->setRoute($routeName);
            $page->setCacheTime();
        }

        return $page;
    }
}
