<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * ActivityGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
