<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * ColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColumnRepository extends \Doctrine\ORM\EntityRepository
{
}
