<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * LearningGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearningGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
