<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * PeriodActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
