<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
