<?php

namespace Busybee\TimeTableBundle\Repository;

use Busybee\InstituteBundle\Entity\Space;
use Busybee\Core\CalendarBundle\Entity\Year;
use Busybee\People\StaffBundle\Entity\Staff;

/**
 * PeriodActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodActivityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Staff $staff
     * @param Year $year
     * @return array
     */
    public function findByTutor(Staff $staff, Year $year)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.tutor1', 't')
            ->leftJoin('a.tutor2', 'u')
            ->leftJoin('a.tutor3', 'v')
            ->leftJoin('a.activity', 'b')
            ->leftJoin('b.year', 'y')
            ->where('y.id = :year_id')
            ->setParameter('year_id', $year->getId())
            ->andWhere('t.id = :tutor1_id')
            ->setParameter('tutor1_id', $staff->getId())
            ->orWhere('u.id = :tutor2_id')
            ->setParameter('tutor2_id', $staff->getId())
            ->orWhere('v.id = :tutor3_id')
            ->setParameter('tutor3_id', $staff->getId())
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Space $space
     * @param Year $year
     * @return array
     */
    public function findBySpace(Space $space, Year $year)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.space', 's')
            ->leftJoin('a.activity', 'b')
            ->leftJoin('b.year', 'y')
            ->where('y.id = :year_id')
            ->setParameter('year_id', $year->getId())
            ->andWhere('s.id = :space_id')
            ->setParameter('space_id', $space->getId())
            ->getQuery()
            ->getResult();
    }

}
