<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * StartRotateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StartRotateRepository extends \Doctrine\ORM\EntityRepository
{
}
