<?php

namespace Busybee\TimeTableBundle\Repository;

/**
 * TimeTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeTableRepository extends \Doctrine\ORM\EntityRepository
{
}
