<?php

namespace Busybee\People\PersonBundle\Repository;

/**
 * PersonExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonExtraRepository extends \Doctrine\ORM\EntityRepository
{
}
