<?php

namespace Busybee\InstituteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstituteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstituteRepository extends EntityRepository
{
	public function find($id)
	{
		$x = $this->findAll();
		if (! empty($x))
			return $x[0];
		else
			return $this->createEntity();
	}
	
	public function createEntity(){
		
		return new Institute ();
	}
}
