<?php

namespace Busybee\AttendanceBundle\Repository;

/**
 * AttendancePeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendancePeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
