<?php

namespace Busybee\RecordBundle\Entity;

/**
 * StringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByRecordField($rid, $fid)
	{
		$entity = $this->findOneBy(array(
				'record'	=>	$rid,
				'field'	=>	$fid,
			)
		);
		if (empty($entity))
			$entity = $this->createNew();
		return $entity;
	}

	public function findByRecordTable($rid, $tid)
	{
		$entity = $this->findBy(array(
				'record'	=>	$rid,
				'table'	=>	$tid,
			)
		);
		return $entity;
	}
}
