<?php

namespace Busybee\RecordBundle\Entity;

/**
 * EnumTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnumTypeRepository extends BaseRepository
{
	public function createNew()
	{
		$record = new EnumType();
		$record->setCreatedOn(new \DateTime('now'));
		return $record ;
	}
}
