<?php

namespace Busybee\RecordBundle\Entity;

/**
 * DateTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearTypeRepository extends BaseRepository
{
	public function createNew()
	{
		return new YearType();
	}
	
	public function findOneBy( array $criteria)
	{
		$result = parent::findOneBy($criteria);
		if (empty($result))
			$result = $this->createNew();
		return $result;
	}
}
