<?php

namespace Busybee\DatabaseBundle\Entity;

/**
 * EnumeratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnumeratorRepository extends \Doctrine\ORM\EntityRepository
{
	public function createNew()
	{
		return new \Busybee\DatabaseBundle\Entity\Enumerator();
	}
}
