<?php

namespace Busybee\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRepository extends EntityRepository
{
	public function createNew()
	{
		return new Table();
	}
	
	public function findOneBy( array $criteria)
	{
		$table = parent::findOneBy($criteria);
		if (! empty($table))
		{
			if (! empty($table->getSelectParent()))
				$table->getSelectParent()->getId();
			if (! empty($table->getSelectRole()) )
				$table->getSelectRole()->getId();
		}
		return $table;
	}
}
