<?php

namespace Busybee\CampusBundle\Repository;

/**
 * CampusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampusRepository extends \Doctrine\ORM\EntityRepository
{
}
