<?php

namespace Busybee\SecurityBundle\Entity;


use Doctrine\ORM\EntityManager ;
use Doctrine\ORM\Mapping\ClassMetadata ;
/**
 * FailureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FailureRepository extends \Doctrine\ORM\EntityRepository
{

	private $count;
	private $period;
	private $exceptions;

	public function createNew()
	{
		return new \Busybee\SecurityBundle\Entity\Failure();
	}
	/**
	 * Test Remote Address
	 *
	 * @return boolean
	 */
	public function testRemoteAddress($ip)
	{
		if ($this->exceptedIP($ip))
			return true;
		$record = $this->findOneBy(array('address' => $ip));
		if (empty($record))
			return true;
		if ($record->getFailures() < $this->count)
			return true;
		if (strtotime('now') > ($record->getLastModified()->getTimeStamp() + $this->period))
			return true;
		return false;
	}

	public function __construct(EntityManager $em, ClassMetadata $entity, $count, $period, $exceptions)
	{
		parent::__construct($em, $entity);
		$this->period = $period;
		$this->count = $count;
		$this->exceptions = $exceptions;
		return $this;
	}	
	
	public function exceptedIP($ip)
	{
		return in_array($ip, $this->exceptions);	
	}
}
