<?php

namespace Busybee\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Busybee\SecurityBundle\Entity\Group;
/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

	public function saveGroup(Group $group) {
		
		$em = $this->getManager();

		$em->persist($group);
		$em->flush();
		return $group;
	}

}
