<?php

namespace Busybee\PersonBundle\Repository;

/**
 * EmergencyContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmergencyContactRepository extends \Doctrine\ORM\EntityRepository
{
}
