<?php

namespace Busybee\Core\SystemBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Busybee\Core\SecurityBundle\Entity\User;
use Busybee\Core\SystemBundle\Entity\Setting;

/**
 * SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @version    28th November 2016
 * @since      20th October 2016
 * @author     Craig Rayner
 */
class SettingRepository extends EntityRepository
{

	protected $setting;
	protected $currentUser;

	/**
	 * get Current User
	 *
	 * @version    26th October 2016
	 * @since      26th October 2016
	 * @return    Entity/User
	 */
	public function getCurrentUser()
	{
		return $this->currentUser;
	}

	/**
	 * set Current User
	 *
	 * @version    26th October 2016
	 * @since      26th October 2016
	 *
	 * @param    Entity /User
	 *
	 * @return    this
	 */
	public function setCurrentUser($user)
	{
		$this->currentUser = $user;

		return $this;
	}

	/**
	 * find One By Name
	 *
	 * @version    28th November 2016
	 * @since      28th November 2016
	 * @return    Entity/Setting
	 */
	public function findOneByName($name)
	{
		$this->setting = parent::findOneByName($name);
		if (is_null($this->setting))
			$this->setting = new Setting();

		return $this->setting;
	}
}
